# Deploys cloudskew-landing to testing environment (blob storage accessed via cdn).

name: cloudskew-cdn.test

pool:
  vmImage: ubuntu-latest

variables:
  - template: azure-pipelines.template.yml

stages:
  - template: azure-pipelines.template.yml