# Deploys cloudskew-assets to testing environment (blob storage accessed via cdn).

pool:
  vmImage: ubuntu-18.04

trigger:
  - master

pr: none

name: cloudskew-assets.testing

variables:
  - group: cloudskew-variable-group

stages:
  - template: templates/stages.yml
    parameters:
      azureSubscription: $(testing-service-connection)
      cdnEndpointName: $(testing-cdnendpoint-name-cloudskew-cdn)
      cdnProfileName: $(testing-cdnprofile-name-cloudskew-cdn)
      cdnResourceGroupName: $(testing-resource-group-cloudskew-cdn)
      environment: testing
      storageAccountName: $(testing-storageaccount-name-cloudskew-cdn)
