# Deploys cloudskew-assets to production environment (blob storage accessed via cdn).

pool:
  vmImage: ubuntu-latest

trigger: none

name: cloudskew-assets.production

variables:
  - group: cloudskew-variable-group

stages:
  - template: templates/stages.yml
    parameters:
      azureSubscription: $(production-service-connection)
      environment: production
      storageAccountName: $(production-storageaccount-name-cloudskew-cdn)
