# Deploys cloudskew-landing to testing environment (blob storage accessed via cdn).

pool:
  vmImage: ubuntu-latest

trigger:
  - master

name: cloudskew-cdn.testing

variables:
  - group: cloudskew-variable-group

stages:
  - template: templates/stages.yml
    parameters:
      azureSubscription: $(testing-service-connection)
      environment: testing
      storageAccountName: $(testing-storageaccount-name-cloudskew-cdn)
